### ISSUE TITLE
Static build file is corrupted

### ISSUE THREAD

**Issue by mterron** [PostgREST/postgrest#1344]
### Description of issue
`postgrest-v6.0.0-linux-x64-static.tar.xz` fail to decompress by tar
```bash
/ # tar -xJvf postgrest-v6.0.0-linux-x64-static.tar.xz
tar: corrupted data
tar: short read
```
I manage to decompress the file using 7zip on Windows. 

EDIT: Corrected filename to reflect static release.

**Comment by steve-chavez** [comment]
I can't reproduce, `tar -xJvf` succeeds with no error.

Are you on Windows? Maybe `tar` is different there.

Btw, there's no release for Windows yet, see https://github.com/PostgREST/postgrest/issues/1334.

**Comment by mterron** [comment]
Not, I'm on linux (native, no vm or container). Maybe there's some bad files on a CDN, I got consistent corruption yesterday with both GNU tar and Busybox tar.

The only way I manage to get ahold of a file that worked was using a windows desktop and unpacking with 7zip.

**Comment by mterron** [comment]
I discovered what the issue is: `postgrest-v6.0.0-linux-x64-static.tar.xz` is not xz compressed, it is just a plain tar file.

Please rename it to `postgrest-v6.0.0-linux-x64-static.tar` or actualy xz compress it.

**Comment by steve-chavez** [comment]
@mterron You're right about the static build, I actually tried `postgrest-v6.0.0-ubuntu.tar.xz` since that was the tar you mentioned in your original issue.

I've now corrected the release:
```
file postgrest-v6.0.0-linux-x64-static.tar.xz
postgrest-v6.0.0-linux-x64-static.tar.xz: XZ compressed data
```

See if it works for you https://github.com/PostgREST/postgrest/releases/download/v6.0.0/postgrest-v6.0.0-linux-x64-static.tar.xz

**Comment by steve-chavez** [comment]
Thanks for the report @mterron . Should be fixed by now, closing.

**Comment by alguintu** [comment]
I'm getting tar: short read on [postgrest-v9.0.0-linux-static-x64.tar.xz](https://github.com/PostgREST/postgrest/releases/download/v9.0.0/postgrest-v9.0.0-linux-static-x64.tar.xz) when building on docker. Tried renaming to plain tar, but still getting the same issue. Any ideas to solve would be appreciated. Thank you.

**Comment by steve-chavez** [comment]
@alguintu Have you tried the already available docker image? https://hub.docker.com/r/postgrest/postgrest/
